export class Work {
    public id: Number
    public company_id : Number
    public code: String
    public discharge_date: Date
    public name: String
    public first_name: String
    public last_name: String
    public contract_type_id: Number
    public period_type_id: Number
    public real_daily_salary: Number
    public imss_daily_salary: Number
    public contribution_base_salary: Number
    public contribution_base_id: Number
    public department_id: Number
    public job_id: Number
    public employee_type_id: Number
    public payment_method_id: Number
    public work_shift_id: Number
    public number_afore: String
    public social_security_number: String
    public rfc: String
    public curp: String
    public sex_id: Number
    public birth_city: String
    public birth_date: Date
    public umf: String
    public fathers_name: String
    public mothers_name: String
    public current_address: String
    public current_population: String
    public current_state: String
    public cp: String
    public telephone: String
    public back_electronic_payment: String
    public acount_number: String
    public branch_office: String
    public fonacot_number: String
    public email: String
    public key_account: String
    public state: String
    public infonavit_credit_number: String
    public discount_type_id: Number
    public monthly_factor: String
    public created_at?: String
    public updated_at?: String
    public deleted_at?: String
    public loader?:Boolean = false
}